#include "ui_game_main_window.h"

void Ui_GameMainWindow::setupUi(QMainWindow *GameMainWindow) {
    if (GameMainWindow->objectName().isEmpty()) {
        GameMainWindow->setObjectName(QString::fromUtf8("GameMainWindow"));
    }
    GameMainWindow->resize(980, 700);
    GameMainWindow->setMinimumSize(QSize(520, 350));
    centralwidget = new QWidget(GameMainWindow);
    centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
    centralwidget->setMinimumSize(QSize(0, 0));
    verticalLayout_5 = new QVBoxLayout(centralwidget);
    verticalLayout_5->setObjectName(QString::fromUtf8("verticalLayout_5"));
    horizontalLayout = new QHBoxLayout();
    horizontalLayout->setSpacing(7);
    horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
    horizontalLayout->setSizeConstraint(QLayout::SetDefaultConstraint);
    field = new GameField(centralwidget);
    field->setObjectName(QString::fromUtf8("field"));
    QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
    sizePolicy.setHorizontalStretch(0);
    sizePolicy.setVerticalStretch(0);
    sizePolicy.setHeightForWidth(field->sizePolicy().hasHeightForWidth());
    field->setSizePolicy(sizePolicy);
    field->setMinimumSize(QSize(310, 300));
    field->setMouseTracking(false);
    field->setAutoFillBackground(false);
    horizontalLayout->addWidget(field);
    options = new QWidget(centralwidget);
    options->setObjectName(QString::fromUtf8("options"));
    QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
    sizePolicy1.setHorizontalStretch(0);
    sizePolicy1.setVerticalStretch(0);
    sizePolicy1.setHeightForWidth(options->sizePolicy().hasHeightForWidth());
    options->setSizePolicy(sizePolicy1);
    options->setMinimumSize(QSize(200, 300));
    options->setAutoFillBackground(false);
    verticalLayout_6 = new QVBoxLayout(options);
    verticalLayout_6->setObjectName(QString::fromUtf8("verticalLayout_6"));
    verticalLayout_7 = new QVBoxLayout();
    verticalLayout_7->setObjectName(QString::fromUtf8("verticalLayout_7"));
    load_button = new QPushButton(options);
    load_button->setObjectName(QString::fromUtf8("load_button"));
    verticalLayout_7->addWidget(load_button);
    info = new QLabel(options);
    info->setObjectName(QString::fromUtf8("info"));
    verticalLayout_7->addWidget(info);
    reset_button = new QPushButton(options);
    reset_button->setObjectName(QString::fromUtf8("reset_button"));
    verticalLayout_7->addWidget(reset_button);
    gridLayout = new QGridLayout();
    gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
    gridLayout->setSizeConstraint(QLayout::SetDefaultConstraint);
    gridLayout->setContentsMargins(-1, 0, -1, -1);
    to_born_box = new QGroupBox(options);
    to_born_box->setObjectName(QString::fromUtf8("to_born_box"));
    sizePolicy1.setHeightForWidth(to_born_box->sizePolicy().hasHeightForWidth());
    to_born_box->setSizePolicy(sizePolicy1);
    to_born_box->setFlat(false);
    horizontalLayout_3 = new QHBoxLayout(to_born_box);
    horizontalLayout_3->setSpacing(0);
    horizontalLayout_3->setObjectName(QString::fromUtf8("horizontalLayout_3"));
    verticalLayout = new QVBoxLayout();
    verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
    b_zero = new QCheckBox(to_born_box);
    to_born_buttons = new QButtonGroup(GameMainWindow);
    to_born_buttons->setObjectName(QString::fromUtf8("to_born_buttons"));
    to_born_buttons->setExclusive(false);
    to_born_buttons->addButton(b_zero);
    b_zero->setObjectName(QString::fromUtf8("b_zero"));
    b_zero->setMouseTracking(false);
    verticalLayout->addWidget(b_zero);
    b_one = new QCheckBox(to_born_box);
    to_born_buttons->addButton(b_one);
    b_one->setObjectName(QString::fromUtf8("b_one"));
    b_one->setMouseTracking(false);
    verticalLayout->addWidget(b_one);
    b_two = new QCheckBox(to_born_box);
    to_born_buttons->addButton(b_two);
    b_two->setObjectName(QString::fromUtf8("b_two"));
    b_two->setMouseTracking(false);
    verticalLayout->addWidget(b_two);
    b_three = new QCheckBox(to_born_box);
    to_born_buttons->addButton(b_three);
    b_three->setObjectName(QString::fromUtf8("b_three"));
    b_three->setMouseTracking(false);
    verticalLayout->addWidget(b_three);
    b_four = new QCheckBox(to_born_box);
    to_born_buttons->addButton(b_four);
    b_four->setObjectName(QString::fromUtf8("b_four"));
    b_four->setMouseTracking(false);
    verticalLayout->addWidget(b_four);
    horizontalLayout_3->addLayout(verticalLayout);
    verticalLayout_2 = new QVBoxLayout();
    verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
    b_five = new QCheckBox(to_born_box);
    to_born_buttons->addButton(b_five);
    b_five->setObjectName(QString::fromUtf8("b_five"));
    b_five->setMouseTracking(false);
    verticalLayout_2->addWidget(b_five);
    b_six = new QCheckBox(to_born_box);
    to_born_buttons->addButton(b_six);
    b_six->setObjectName(QString::fromUtf8("b_six"));
    b_six->setMouseTracking(false);
    verticalLayout_2->addWidget(b_six);
    b_seven = new QCheckBox(to_born_box);
    to_born_buttons->addButton(b_seven);
    b_seven->setObjectName(QString::fromUtf8("b_seven"));
    b_seven->setMouseTracking(false);
    verticalLayout_2->addWidget(b_seven);
    b_eight = new QCheckBox(to_born_box);
    to_born_buttons->addButton(b_eight);
    b_eight->setObjectName(QString::fromUtf8("b_eight"));
    b_eight->setMouseTracking(false);
    verticalLayout_2->addWidget(b_eight);
    horizontalLayout_3->addLayout(verticalLayout_2);
    gridLayout->addWidget(to_born_box, 0, 0, 1, 1);
    to_survive_box = new QGroupBox(options);
    to_survive_box->setObjectName(QString::fromUtf8("to_survive_box"));
    sizePolicy1.setHeightForWidth(to_survive_box->sizePolicy().hasHeightForWidth());
    to_survive_box->setSizePolicy(sizePolicy1);
    to_survive_box->setFlat(false);
    horizontalLayout_4 = new QHBoxLayout(to_survive_box);
    horizontalLayout_4->setSpacing(0);
    horizontalLayout_4->setObjectName(QString::fromUtf8("horizontalLayout_4"));
    verticalLayout_3 = new QVBoxLayout();
    verticalLayout_3->setObjectName(QString::fromUtf8("verticalLayout_3"));
    s_zero = new QCheckBox(to_survive_box);
    to_survive_buttons = new QButtonGroup(GameMainWindow);
    to_survive_buttons->setObjectName(QString::fromUtf8("to_survive_buttons"));
    to_survive_buttons->setExclusive(false);
    to_survive_buttons->addButton(s_zero);
    s_zero->setObjectName(QString::fromUtf8("s_zero"));
    s_zero->setMouseTracking(false);
    verticalLayout_3->addWidget(s_zero);
    s_one = new QCheckBox(to_survive_box);
    to_survive_buttons->addButton(s_one);
    s_one->setObjectName(QString::fromUtf8("s_one"));
    s_one->setMouseTracking(false);
    verticalLayout_3->addWidget(s_one);
    s_two = new QCheckBox(to_survive_box);
    to_survive_buttons->addButton(s_two);
    s_two->setObjectName(QString::fromUtf8("s_two"));
    s_two->setMouseTracking(false);
    verticalLayout_3->addWidget(s_two);
    s_three = new QCheckBox(to_survive_box);
    to_survive_buttons->addButton(s_three);
    s_three->setObjectName(QString::fromUtf8("s_three"));
    s_three->setMouseTracking(false);
    verticalLayout_3->addWidget(s_three);
    s_four = new QCheckBox(to_survive_box);
    to_survive_buttons->addButton(s_four);
    s_four->setObjectName(QString::fromUtf8("s_four"));
    s_four->setMouseTracking(false);
    verticalLayout_3->addWidget(s_four);
    horizontalLayout_4->addLayout(verticalLayout_3);
    verticalLayout_4 = new QVBoxLayout();
    verticalLayout_4->setObjectName(QString::fromUtf8("verticalLayout_4"));
    s_five = new QCheckBox(to_survive_box);
    to_survive_buttons->addButton(s_five);
    s_five->setObjectName(QString::fromUtf8("s_five"));
    s_five->setMouseTracking(false);
    verticalLayout_4->addWidget(s_five);
    s_six = new QCheckBox(to_survive_box);
    to_survive_buttons->addButton(s_six);
    s_six->setObjectName(QString::fromUtf8("s_six"));
    s_six->setMouseTracking(false);
    verticalLayout_4->addWidget(s_six);
    s_seven = new QCheckBox(to_survive_box);
    to_survive_buttons->addButton(s_seven);
    s_seven->setObjectName(QString::fromUtf8("s_seven"));
    s_seven->setMouseTracking(false);
    verticalLayout_4->addWidget(s_seven);
    s_eight = new QCheckBox(to_survive_box);
    to_survive_buttons->addButton(s_eight);
    s_eight->setObjectName(QString::fromUtf8("s_eight"));
    s_eight->setMouseTracking(false);
    verticalLayout_4->addWidget(s_eight);
    horizontalLayout_4->addLayout(verticalLayout_4);
    gridLayout->addWidget(to_survive_box, 0, 1, 1, 1);
    verticalLayout_7->addLayout(gridLayout);
    verticalSpacer = new QSpacerItem(20, 40, QSizePolicy::Minimum, QSizePolicy::Expanding);
    verticalLayout_7->addItem(verticalSpacer);
    horizontalLayout_2 = new QHBoxLayout();
    horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
    horizontalLayout_2->setSizeConstraint(QLayout::SetMinimumSize);
    speed_box = new QSpinBox(options);
    speed_box->setObjectName(QString::fromUtf8("speed_box"));
    speed_box->setReadOnly(false);
    speed_box->setButtonSymbols(QAbstractSpinBox::PlusMinus);
    speed_box->setMinimum(1);
    speed_box->setMaximum(5);
    horizontalLayout_2->addWidget(speed_box);
    play_button = new QPushButton(options);
    play_button->setObjectName(QString::fromUtf8("play_button"));
    horizontalLayout_2->addWidget(play_button);
    verticalLayout_7->addLayout(horizontalLayout_2);
    stop_button = new QPushButton(options);
    stop_button->setObjectName(QString::fromUtf8("stop_button"));
    verticalLayout_7->addWidget(stop_button);
    verticalLayout_6->addLayout(verticalLayout_7);
    horizontalLayout->addWidget(options);
    horizontalLayout->setStretch(0, 1);
    verticalLayout_5->addLayout(horizontalLayout);
    GameMainWindow->setCentralWidget(centralwidget);
    statusbar = new QStatusBar(GameMainWindow);
    statusbar->setObjectName(QString::fromUtf8("statusbar"));
    GameMainWindow->setStatusBar(statusbar);
    retranslateUi(GameMainWindow);
    QMetaObject::connectSlotsByName(GameMainWindow);
}

void Ui_GameMainWindow::retranslateUi(QMainWindow *GameMainWindow) {
    GameMainWindow->setWindowTitle(QCoreApplication::translate("GameMainWindow", "Conway's Game of Life", nullptr));
    load_button->setText(QCoreApplication::translate("GameMainWindow", "Load file", nullptr));
    info->setText(QString());
    reset_button->setText(QCoreApplication::translate("GameMainWindow", "Reset", nullptr));
    to_born_box->setTitle(QCoreApplication::translate("GameMainWindow", "Rule to born:", nullptr));
    b_zero->setText(QCoreApplication::translate("GameMainWindow", "0", nullptr));
    b_one->setText(QCoreApplication::translate("GameMainWindow", "1", nullptr));
    b_two->setText(QCoreApplication::translate("GameMainWindow", "2", nullptr));
    b_three->setText(QCoreApplication::translate("GameMainWindow", "3", nullptr));
    b_four->setText(QCoreApplication::translate("GameMainWindow", "4", nullptr));
    b_five->setText(QCoreApplication::translate("GameMainWindow", "5", nullptr));
    b_six->setText(QCoreApplication::translate("GameMainWindow", "6", nullptr));
    b_seven->setText(QCoreApplication::translate("GameMainWindow", "7", nullptr));
    b_eight->setText(QCoreApplication::translate("GameMainWindow", "8", nullptr));
    to_survive_box->setTitle(QCoreApplication::translate("GameMainWindow", "Rule to survive:", nullptr));
    s_zero->setText(QCoreApplication::translate("GameMainWindow", "0", nullptr));
    s_one->setText(QCoreApplication::translate("GameMainWindow", "1", nullptr));
    s_two->setText(QCoreApplication::translate("GameMainWindow", "2", nullptr));
    s_three->setText(QCoreApplication::translate("GameMainWindow", "3", nullptr));
    s_four->setText(QCoreApplication::translate("GameMainWindow", "4", nullptr));
    s_five->setText(QCoreApplication::translate("GameMainWindow", "5", nullptr));
    s_six->setText(QCoreApplication::translate("GameMainWindow", "6", nullptr));
    s_seven->setText(QCoreApplication::translate("GameMainWindow", "7", nullptr));
    s_eight->setText(QCoreApplication::translate("GameMainWindow", "8", nullptr));
    play_button->setText(QCoreApplication::translate("GameMainWindow", "Play", nullptr));
    stop_button->setText(QCoreApplication::translate("GameMainWindow", "Stop", nullptr));
}
